<?php

/* ----------------------------------

    CHARACTER DATABASE

----------------------------------- */


// [ ID, HANDLE, FULLNAME ]
return [
    [ 55, 'bay', 'Bayonetta'        ],
    [  4, 'bow', 'Bowser'           ],
    [ 39, 'bjr', 'Bowser Jr.'       ],
    [ 26, 'cfc', 'Captain Falcon'   ],
    [ 24, 'chz', 'Charizard'        ],
    [ 54, 'cld', 'Cloud'            ],
    [ 43, 'cor', 'Corrin'           ],
    [ 45, 'dkp', 'Dark Pit'         ],
    [  8, 'ddk', 'Diddy Kong'       ],
    [  7, 'dkk', 'Donkey Kong'      ],
    [ 50, 'dkh', 'Duck Hunt'        ],
    [  5, 'drm', 'Dr. Mario'        ],
    [ 20, 'fal', 'Falco'            ],
    [ 19, 'fox', 'Fox'              ],
    [ 12, 'gan', 'Ganondorf'        ],
    [ 40, 'gre', 'Greninja'         ],
    [ 31, 'ike', 'Ike'              ],
    [ 22, 'jig', 'Jigglypuff'       ],
    [ 18, 'ddd', 'King Dedede'      ],
    [ 16, 'kby', 'Kirby'            ],
    [  9, 'lnk', 'Link'             ],
    [ 47, 'lmc', 'Little Mac'       ],
    [ 25, 'lcr', 'Lucario'          ],
    [ 28, 'luc', 'Lucas'            ],
    [ 42, 'lcn', 'Lucina'           ],
    [  2, 'lui', 'Luigi'            ],
    [  1, 'mar', 'Mario'            ],
    [ 29, 'mth', 'Marth'            ],
    [ 51, 'mgm', 'Mega Man'         ],
    [ 17, 'mtk', 'Meta Knight'      ],
    [ 23, 'mew', 'Mewtwo'           ],
    [ 32, 'mgw', 'Mr. Game & Watch' ],
    [ 27, 'nes', 'Ness'             ],
    [ 35, 'oli', 'Olimar'           ],
    [ 52, 'pac', 'Pac-Man'          ],
    [ 44, 'pal', 'Palutena'         ],
    [  3, 'pea', 'Peach'            ],
    [ 21, 'pik', 'Pikachu'          ],
    [ 32, 'pit', 'Pit'              ],
    [ 36, 'rob', 'R.O.B.'           ],
    [ 41, 'rbn', 'Robin'            ],
    [ 38, 'rsl', 'Rosalina & Luma'  ],
    [ 30, 'roy', 'Roy'              ],
    [ 53, 'ryu', 'Ryu'              ],
    [ 14, 'sam', 'Samus'            ],
    [ 37, 'son', 'Sonic'            ],
    [ 11, 'shk', 'Sheik'            ],
    [ 49, 'shu', 'Shulk'            ],
    [ 13, 'tlk', 'Toon Link'        ],
    [ 46, 'vil', 'Villager'         ],
    [ 34, 'war', 'Wario'            ],
    [ 48, 'wft', 'Wii Fit Trainer'  ],
    [  6, 'yos', 'Yoshi'            ],
    [ 10, 'zel', 'Zelda'            ],
    [ 15, 'zss', 'Zero Suit Samus'  ],
];
